<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Медиа диалоги</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Диалоги выбора медиафайлов с возможностью указания параметров отображения.</p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">Список медиа диалогов</a></li>
        <li><a href="<?= $url('form') ?>">Форма добавления / редактирования медиа диалога</a></li>
    </ul>
</article>